### PR TITLE
Adding the Getlist class, based on get_list, to allow searches of supdoc and supdocfolders

### PR DESCRIPTION
**Pull request by craibuc**
Adding the `Getlist` class, based on get_list, to allow searches of `supdoc` and `supdocfolders`.

### CODE REVIEW

**Comment by craibuc** [comment]
Is there something that I need to do get this pull merged?

**Comment by AlanBarber** [comment]
Looks like some unit tests are failing but appears that the project development has gone dark. Hasn't been any activity by the owners since November.

**Comment by dylan-holt-sage** [comment]
Hey @craibuc, I'm working on fixing the issue now :) apologies for the long delay in response.

**Comment by dylan-holt-sage** [comment]
Made additional changes to a branch off of the one in this PR and merged. Thanks for your contribution.
https://github.com/Intacct/intacct-sdk-net/pull/175

**Pull request closed without merging**
